# Dependabot will run on day 21 of each month at 02:22 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      day: 8
      timezone: "Europe/Berlin"
      cronjob: "22 2 21 * *"
    open-pull-requests-limit: 15
    assignees:
      - "minukodu"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 8
      timezone: "Europe/Berlin"
      cronjob: "22 2 21 * *"
    open-pull-requests-limit: 15
    assignees:
      - "minukodu"
